### ISSUE TITLE
API Issues ITF has seen with the spec

### ISSUE THREAD

**Issue by JTEnglish** [robinjanette/OATS_API#1] opened 2018-03-30 15:24 UTC
#### Changes On ITF's End
- We will be getting rid of the prof key in course and assignment endpoints 
- We are going to have our return for the run_test endpoint be in the form of
   { id: true | false, id2: true | false...}

#### Remaining Issues Without a Solution and Questions
- With in the /api/user/test endpoint the test_file key has a value of testcase_contents should that be base 64 encoded? Other items in the spec say that. 
- We don't see the need for a prof endpoint 
    - In the /api/role we should have the functionality of the /api/prof endpoint

**Comment by robinjanette** [comment] 2018-03-30 15:26
In regards to the first bullet for Remaining Issues, yes the test_file contents are base64 encoded and zipped for both the input sent to the testserver and the output sent back to the webserver

**Comment by robinjanette** [comment] 2018-03-30 15:29
In regards to the second bullet, having a separate endpoint for adding a professor is more secure, as role will be used by students and TA's, but /professor is only used by the admin. The professor endpoint was agreed upon in our meeting on February 7th, and we do not believe that removing this endpoint from the specification at this point is necessary.

**Comment by Austin-Crabtree** [comment] 2018-03-31 17:15
### Response to previous comment:
So in regards to your previous comment about the role and professor endpoint, this API specification was created with the philosophy in mind that it is agnostic to the implementation of the testing server. It seems that this is used as a dependency to your server that we do not have in ours, which is why we would like to discuss a solution that we all agree on that is agnostic to either server implementation.

### Our suggested solution: 
 Our suggested solution to this is to get rid of the /api/professor endpoint and wrap its duty into the /api/role endpoint. Below is a look on our suggested change: 

   /api/role
   Post - {user, "course": "ID"} or when user has role Admin then {user, prof} the prof object has the   
   following keys and values "prof": {"uid":"uid", "role":"P", "name":"name"} this object will be used later
   Put - {user, "course": "ID"} there would be no need for a admin case here
   Delete - {user, "course": "ID"} or {user, prof}

To help you mitigate to changes you would need to make you can have a if statement in the Post and Delete methods that will check if the users is an admin and that he prof object exists then you execute the current code that y'all have in your /api/professor endpoint

### Other Comments: 
We also noted that in the current /api/professor endpoint there is no validation that the user that sent this is an admin and so that would need to be added in the current proposal by your team.

**Comment by robinjanette** [comment] 2018-03-31 19:20
Hey there ITF. I have reviewed your comments and suggestions. I would be willing to add two keys to the /api/professor endpoint, one for the unique ID of the user adding the professor and one that would serve as a password for the user adding the professor to the testserver. I am also curious why you believe that one shared endpoint is more secure than two, given the distinct functionality of adding a privileged professor user versus adding a user of any level to a course.

However, that change to the role endpoint still does not work for our testserver because we must know the user's name and role in order to validate that a user has the required permissions in a given course. If these keys were eliminated, then we would lose key functionality, namely the ability for professors to have TA's for their courses, which our client and professor user testers have greatly appreciated. This would also make our database less effective for keeping track of users and permissions, if we have no idea what role a user has in a course, which also impacts the security of our two systems.

As you are still implementing the API, it seems to our team that it would be easier for me to help you write your new API calls rather than to refactor large parts of ours. I am willing to send skeleton code for your /api/professor endpoint such that all you would need to do is modify the JWT section as well as the database queries. 

Please let me know what you think about these comments and concerns.

**Comment by Austin-Crabtree** [comment] 2018-03-31 19:56
#### For your first point:
In the above suggestion we weren't meaning to imply security. We are meaning to create an API that isn't dependent on any one  testing server implementation which our client has posed as the requirement, and the way these endpoints are right now are standing only to meet your testing server requirements and we don't find the need for two separate endpoints. 
 
#### For your second point: 
As per the above suggestion the /api/role endpoint would maintain the same keys that you would need. The user object with all the information you are needing is in the json. We are only suggesting to send a different json structure when an admin is adding a professor in which case instead of the course key there would be the prof object with the needed info for a prof inside. And in your endpoint you can test if the user is an admin and if the prof object exists then you can execute the code you have for your /api/professor endpoint

#### For your third point: 
We are not still implementing the API we currently working on the specifications, since we are not in agreement on this that makes it not apart of the specification and until we meet an agreement, we are not required to move forward with implementing these endpoints. While I appreciate the offer for skeleton code it is unnecessary unless we can agree on this. 

#### Overall: 
Now hopefully the above has cleared up anything that might have been unclear is there any parts of our above suggestion that are still lacking? or would you like to give a counter suggestion that would improve on the idea of making this not solely dependent on a single implementation of a testing server.

**Comment by tbsteinb** [comment] 2018-03-31 20:20
Security is an extremely important aspect of this project. Adding the prof API endpoint is more secure than relying on role (which is meant for something completely different for us anyway) take on extra functionality. It would be far more efficient for you to implement a relatively small endpoint than for us to scratch it and then completely rework an already existing endpoint. All your test server end would need to do is just ignore it basically.

I don't know why you didn't look at these specifications earlier, but in my view you have brought this on yourselves. We've had this repo for this very purpose since the start of the project and the intent was that this _is_ the specification. If you had a problem with it you really should have brought it up sooner.

If you are really concerned about the extra work (which is what your concern seems to be) then just let Robin give you the skeleton code. This seems to be the fastest way to getting an API merge.

**Comment by JTEnglish** [comment] 2018-03-31 21:03
#### In response to treating the word document as the agreed upon specifications
In the first meeting with the API teams this semester, when we went over the word document, ITF had brought up the issue of not having an agreed method for dealing with users on the testing serveres in reference to the /api/professor and /api/role endpoints. If I remember correctly, we left that point of the discussion saying we would have to agree on the implementation.

#### In response to "bringing this on ourselves"
In an attempt to clarify the issue earlier this month, Zak had sent an email titled "Dual Authentication" on 3/16/18, asking for input on a proposal for this issue or a counter proposal from TBD. No one responded to the email and ITF did not get any other form of response reguarding the proposal.

As I see it, both teams are at fault in our poor communication and pointing fingers is not going to provide a solution to this roadblock. Making assumptions about our attitudes toward "extra work" only serves to further muddy communication between our groups.

**Comment by tbsteinb** [comment] 2018-03-31 21:10
I'm not trying to point fingers, but trying to make us change something we've had implemented for months is only going to slow everything down. My point was that we've had months to get this figured out, and that this issue is only now getting discussed is a problem. Given that we have one sprint and 1.5 days left, the more sensible solution is for you to implement the prof endpoint. As Robin and I mentioned above, doing it this way is more secure. As it is, our team still has a fair amount of work to do in other areas, so artificially adding work does not make sense.
It is far easier and faster to implement a new endpoint than it is to modify one that already exists to take on functionality it was never meant to have.

**Comment by tbsteinb** [comment] 2018-03-31 21:16
I'd also like to point out that if we never agreed on an implementation, then this issue should have come up much sooner. The whole point of this repo was to be the agreed upon specification. If ITF did not like this, then something should have been said, however having a single document that everyone follows makes far more sense than having each team take their own notes as there would be no way to verify whose copy of the specification is right.

**Comment by robinjanette** [comment] 2018-03-31 21:18
ITF,

The issue with your first point is that you did not actually provide your specification to us in written form at the February 7th meeting. Therefore, the word document is the only specification TBD had to work off of for our API, which was still under development at that point for our team. Had you provided a hard reference for us to work off of, as we did, I would have a better idea what your API looked like and problems such as this could have been avoided.

My understanding of the dual authentication issue was that it would be in addition to the API calls used to create and modify a user (/api/role and /api/professor) and was more of a stretch goal for additional security than a requirement. As Zak's Match 16th email was right before a meeting with the client, Professor Abukamail, and our team, we decided to wait until that meeting to see how this issue would be addressed. In that meeting, it was confirmed that dual authentication was less important than the API merge, and therefore the API calls we set in the specification document are the only communication between testserver and webserver for setting user roles. At that point, we had no idea that you did not see the word document as the specification, and did not anticipate that these two API endpoints would be an issue whatsoever.

**Comment by Austin-Crabtree** [comment] 2018-03-31 21:23
We did bring a written document to said meeting while it wasn't in a word document I had written up each endpoint we had and needed to have to meet the specification as we saw it at that time. As changes were made during the meeting we made note on that paper and I asked if you would like to keep it so that you could have a copy of our notes and you declined to keep it.

**Comment by tbsteinb** [comment] 2018-03-31 21:26
That may be, however it still does not get around the fact that the entire point of this repo was to be the specification. Again, all members of TBD are busy with stuff outside of this project this weekend. We simply do not have time to completely rework an endpoint to add in unrelated functionality. As I said above, implementing an end point that does basically nothing should be very little work, especially since Robin would be able to provide you with the skeleton for that.

**Comment by robinjanette** [comment] 2018-03-31 21:26
I'm sorry but I do not remember that your notes were offered, as I remember being the person primarily taking notes for the meeting. I was also working under the assumption that the specification I wrote up and posted on this Github would be reviewed by your team for any mistakes.

**Comment by tbsteinb** [comment] 2018-03-31 21:28
This is turning into a game of "he said, she said" which is completely unproductive. The fact of the matter is, implementing the prof API call is going to be faster overall, and more secure.

**Comment by Austin-Crabtree** [comment] 2018-03-31 21:39
Saying that because we did not provide you with a written design it was okay to move forward with your own implementation with no indication to us whatsoever beyond updates we were meant to notice to the repo is not acceptable, especially when there were ample indicators we did not know that you were doing so. Zak's email indicated strongly that we did not know there was a specification in place, and could have been met with an answer that there is. As you mentioned, the both-team meeting indicated that the dual-authentication issue was secondary: If you knew you already had an implementation, as you claim, for months, why was this not mentioned if it would affect our own progress?

We would like to move on from this. Accusations, finger pointing, and work ethic critique do not help solve this issue. We need this discussion to stop being a personal issue of ITF vs TDB; it needs to shift gears to being about the two projects. We will implement your requested endpoint as a dummy, as you suggested above, so that you will be able to hit our test server, tomorrow. We are aware this makes us unable to test against your API as our web server has no implementation for handling this, but we are unconcerned and will make the necessary changes next sprint. Is this something you can agree to for the purpose of achieving the goals of this sprint?

**Comment by tbsteinb** [comment] 2018-03-31 21:47
If you thought there was no single documentation, then you should have approached Robin about that issue. However, Stewart outright said this is the specification at the start of the project. It's the _ENTIRE_ reason we have it. Pretending that you had no idea this repo existed and then blaming us for you not looking at it is completely unacceptable. You have known since day 1 of the shared API that this repo existed, you were sent an email to join the repo immediately, and Robin has made countless references to it. That is 100% on you, so don't even begin to claim otherwise.

Our interpretation of the email was that it was in addition to this, not a substitute. As for why we didn't say anything to you, it is because we thought we were all on the same page, however that is clearly not the case.

I'll let Robin make the final call on that last question, but it seems reasonable to me.

**Comment by robinjanette** [comment] 2018-03-31 21:57
I agree that we need to move on, but before we do I strongly disagree with several of your comments in the first paragraph. We did not move forward with our own implementation, as the version that is in the repo was significantly changed from what my team presented in that meeting and our implementation likewise was changed to meet the new specification. Secondly, Zak's email does not mention the API whatsoever, and given the previous comments your team had made about dual authentication I was led to believe that it would not impact the API whatsoever, so I am sorry you assumed we understood differently.

In order to assure you that we would be able to merge the /api/professor endpoint, I would request that we do code review of that endpoint for our system. Would you like me to email our /api/professor endpoint to you? Austin can also access the code in our repo in testserver/var/www/oats-testserver/oats-testserver/__init__.py, starting at line 910. I would also like your input on the authentication of the professor endpoint, which may have to be following this sprint due to time, and as I suggested above, I am fine with adding additional keys to enhance security. 

Can this issue be considered closed, or would you like to keep it open to facilitate communication? I am fine with either option.

**Comment by Austin-Crabtree** [comment] 2018-04-01 18:17
As per the email I am closing this issue.

**Closed as completed by Austin-Crabtree** 2018-04-01 18:17 UTC
